apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: passport-status-api-prod
  app.kubernetes.io/version: 0.0.0
images:
  - name: dtsdevcontainers.azurecr.io/passport-status-api
    newTag: 0.0.0-10f9558e
  - name: mongo
    newTag: 5.0.6
namespace: passport-status