apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: dev
bases:
  - ../../base/passport-status-api/
namespace: passport-status
nameSuffix: -dev
patchesStrategicMerge:
  - passport-status-api-cms.yaml
  - passport-status-api-deployments.yaml
resources:
  - passport-status-api-ingresses.yaml