#######################################################################################################################
#
# Standard Spring Boot properties. Full reference available at:
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
# This application supports configuration overrides using the following resolution order:
#
# 1. The usual Spring Boot configuration resolution:
#    https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
# 2. Config file src/dev/resources/application-local.yaml
#
# To set configuration properties that are local to your development environment
# (for example log levels or database connection strings), create the file
# src/dev/resources/application-local.yaml. This file is not managed by Git, so
# there is no chance of accidentally pushing your custom configuration to the
# project repository.
#
#######################################################################################################################

---

#######################################################################################################################
#
# Actuator properties
#
#######################################################################################################################

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include:
          - beans
          - changelog
          - env
          - health
          - httptrace
          - info
          - init-data
          - metrics
          - refresh
  trace:
    http:
      include:
        - principal
        - remote-address
        - request-headers
        - response-headers
        - time-taken
  metrics:
    export:
      dynatrace:
        enabled: false
        v2:
          metric-key-prefix: passport-status-api

#######################################################################################################################
#
# Server properties
#
#######################################################################################################################

server:
  compression:
    enabled: true
    mime-types:
      - application/hal+json
      # defaults below...
      - application/javascript
      - application/json
      - application/xml
      - text/css
      - text/html
      - text/javascript
      - text/plain
      - text/xml
  shutdown: graceful

#######################################################################################################################
#
# Spring Boot properties
#
#######################################################################################################################

spring:
  application:
    name: passport-status-api
  config:
    import:
      - optional:application-local.yml
      - optional:application-local.yaml
  data:
    mongodb:
      auto-index-creation: true
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 500
  jackson:
    default-property-inclusion: non-null
    serialization:
      indent-output: true
  main:
    allow-bean-definition-overriding: true
  mongodb:
    embedded:
      version: 5.0.6
  security:
    user:
      name: admin

#######################################################################################################################
#
# Springdoc properties
#
#######################################################################################################################

springdoc:
  pre-loading-enabled: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true

#######################################################################################################################
#
# Application-specific properties.
#
#######################################################################################################################

application:
  data-initializer:
    duplicate-statuses-number: 10     # number of duplicate (ie: same data) statuses to generate on startup
    generated-statuses-number: 10_000 # number of random status to generate on startup
    run-on-startup: false             # enable the data initializer on startup; WARNING -- THIS WILL DESTROY DATA
  endpoint:
    changelog:
      changelog-path: changelog.json  # classpath location of the changelog.json file generated during build
  etag-header-filter:
    write-weak-etag: true
  http-trace-repository:
    page-size: 100                    # number of http request/response trace requests to return from /actuator/httptrace
  security:
    cors:
      allowed-headers:                # list of headers that a pre-flight request can list as allowed for use during an actual request
        - '*'
      allowed-methods:                # list of HTTP methods to allow, e.g. GET, POST, PUT, etc.
        - '*'
      allowed-origins:                # list of origins for which cross-origin requests are allowed
        - http://localhost
      exposed-headers:                # list of response headers other than simple headers (i.e. Cache-Control, Content-Language, Content-Type, Expires, Last-Modified, or Pragma) that an actual response might have and can be exposed
        - '*'
  request-logging-filter:
    include-headers: true
    include-payload: true
    include-query-string: true
    max-payload-length: 10240
  swagger:
    application-name: Passport Status API
    contact-name: Digital technology solutions
    contact-url: https://github.com/dts-stn/passport-status-api/
    terms-of-service-url: https://www.canada.ca/en/transparency/terms.html