#######################################################################################################################
#
# Standard Spring Boot properties. Full reference available at:
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
# This application supports configuration overrides using the following resolution order:
#
# 1. The usual Spring Boot configuration resolution:
#    https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
# 2. Config file src/dev/resources/application-local.yaml
#
# To set configuration properties that are local to your development environment
# (for example log levels or database connection strings), create the file
# src/dev/resources/application-local.yaml. This file is not managed by Git, so
# there is no chance of accidentally pushing your custom configuration to the
# project repository.
#
#######################################################################################################################

---

#######################################################################################################################
#
# Actuator properties
#
#######################################################################################################################

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include:
          - beans
          - env
          - health
          - info
          - metrics
          - prometheus
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

#######################################################################################################################
#
# Server properties
#
#######################################################################################################################

server:
  compression:
    enabled: true
    mime-types:
      - application/hal+json
      # defaults below...
      - application/javascript
      - application/json
      - application/xml
      - text/css
      - text/html
      - text/javascript
      - text/plain
      - text/xml
  shutdown: graceful

#######################################################################################################################
#
# Spring Boot properties
#
#######################################################################################################################

spring:
  application:
    name: Passport Status API
  config:
    import:
      - optional:application-local.yml
      - optional:application-local.yaml
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    default-property-inclusion: non-null
    serialization:
      indent-output: true
  main:
    allow-bean-definition-overriding: true
  mongodb:
    embedded:
      version: 5.0.6
  security:
    user:
      name: admin

#######################################################################################################################
#
# Springdoc properties
#
#######################################################################################################################

springdoc:
  packages-to-scan:
    - ca.gov.dtsstn.passport.api.web
  swagger-ui:
    disable-swagger-default-url: true
    showCommonExtensions: true
  writer-with-default-pretty-printer: true

#######################################################################################################################
#
# Application-specific properties.
#
#######################################################################################################################

application:
  dev:
    data-initializer:
      duplicate-statuses-number: 10
      generated-statuses-number: 10_000
  http-trace-repository:
    page-size: 100
  security:
    cors:
      allowed-headers: '*'
      allowed-methods: '*'
      allowed-origins: http://localhost
      exposed-headers: '*'