#######################################################################################################################
#
# Standard Spring Boot properties. Full reference available at:
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
# This application supports configuration overrides using the following resolution order:
#
# 1. The usual Spring Boot configuration resolution:
#    https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
# 2. Config file src/dev/resources/application-local.yaml
#
# To set configuration properties that are local to your development environment
# (for example log levels or database connection strings), create the file
# src/dev/resources/application-local.yaml. This file is not managed by Git, so
# there is no chance of accidentally pushing your custom configuration to the
# project repository.
#
#######################################################################################################################

---

logging:
  level:
    '[ca.gov.dtsstn.passport.api]': info
    '[org.apache.activemq.audit.base]': warn
    '[org.apache.activemq.audit.message]': warn

#######################################################################################################################
#
# Actuator properties
#
#######################################################################################################################

management:
  authorized-role: Application.Manage
  dynatrace:
    metrics:
      export:
        enabled: false
        api-token: # must be set externally (ex: big-random-string)
        uri: # must be set externally (ex: https://dynatrace.example.com/e/00000000-0000-0000-0000-000000000000/api/v2/metrics/ingest)
        v2:
          metric-key-prefix: passport-status-api
  endpoint:
    env:
      show-values: when-authorized
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized
  endpoints:
    jackson:
      isolated-object-mapper: false
    web:
      exposure:
        include:
          - beans
          - changelog
          - env
          - health
          - httpexchanges
          - info
          - initdata
          - metrics
          - prometheus
          - refresh
  httpexchanges:
    recording:
      include:
        - principal
        - remote-address
        - request-headers
        - response-headers
        - time-taken

#######################################################################################################################
#
# Server properties
#
#######################################################################################################################

server:
  compression:
    enabled: true
    mime-types:
      - application/hal+json
      # defaults below...
      - application/javascript
      - application/json
      - application/xml
      - text/css
      - text/html
      - text/javascript
      - text/plain
      - text/xml
  shutdown: graceful

#######################################################################################################################
#
# Spring Boot properties
#
#######################################################################################################################

spring:
  application:
    name: Passport Status API
  artemis:
    embedded:
      queues:
        - passport-statuses
  config:
    import:
      - swagger-ui.yaml
      - optional:application-local.yml
      - optional:application-local.yaml
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 500
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb;COLLATION=ENGLISH STRENGTH PRIMARY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;MODE=PostgreSQL
    hikari: # see https://github.com/brettwooldridge/HikariCP#frequently-used
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  devtools:
    livereload:
      enabled: false
  flyway:
    sql-migration-prefix: v
    sql-migration-separator: '-'
    locations: classpath:db-migrations/common, classpath:db-migrations/{vendor}
  jackson:
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      '[hibernate.batch_versioned_data]': true
      '[hibernate.jdbc.batch_size]': 100
      '[hibernate.order_inserts]': true
      '[hibernate.order_updates]': true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: ${application.security.oauth.client-id}
          issuer-uri: https://login.microsoftonline.com/${application.security.oauth.tenant-id}/v2.0
          jwk-set-uri: https://login.microsoftonline.com/${application.security.oauth.tenant-id}/discovery/v2.0/keys

#######################################################################################################################
#
# Application-specific properties.
#
#######################################################################################################################

application:
  caching:
    enabled: true
    caches:
      esrf-emails:
        expire-after-write: 1
        time-unit: minutes
      status-codes:
        expire-after-write: 5
        time-unit: minutes
  database-initializer:
    duplicate-statuses-number: 10     # number of duplicate (ie: same data) statuses to generate on startup
    generated-statuses-number: 10_000 # number of random status to generate on startup
    run-on-startup: false             # enable the data initializer on startup; WARNING -- THIS WILL DESTROY DATA
  endpoint:
    changelog:
      changelog-path: changelog.json  # classpath location of the changelog.json file generated during build
  gcnotify:
    english-api-key: # must be set externally (ex: 00000000-0000-0000-0000-000000000000)
    french-api-key:  # must be set externally (ex: 00000000-0000-0000-0000-000000000000)
    base-url: https://api.notification.canada.ca/v2/notifications/email
    file-number-notification:
      english-template-id: # must be set externally (ex: 00000000-0000-0000-0000-000000000000)
      french-template-id:  # must be set externally (ex: 00000000-0000-0000-0000-000000000000)
  http-request-repository:
    page-size: 100 # number of http request/response trace requests to return from /actuator/httptrace
    includeUrls:   # list of URLs to include, in ant path style
      - /**
    excludeUrls:   # list of URLs to exclude, in ant path style
      - /actuator/health/liveness
      - /actuator/health/readiness
  jms:
    destination:
      passport-status: passport-statuses
  security:
    content-security-policy:
      default-src: "'self'"
      connect-src: "'self' login.microsoftonline.com"
      img-src: "'self' data:"
      script-src: "'self' 'sha256-4IiDsMH+GkJlxivIDNfi6qk0O5HPtzyvNwVT3Wt8TIw='"
    cors:
      allowed-headers:
        - '*'
      allowed-methods:
        - '*'
      allowed-origins:
        - http://localhost:3000
        - http://localhost:8080
      exposed-headers:
        - '*'
    oauth:
      auth-scopes: ${application.security.oauth.client-id}/.default
      authorization-url: https://login.microsoftonline.com/${application.security.oauth.tenant-id}/oauth2/v2.0/authorize
      client-id: # must be set externally (sample: 00000000-0000-0000-0000-000000000000)
      discovery-url: https://login.microsoftonline.com/${application.security.oauth.tenant-id}/v2.0/.well-known/openid-configuration
      tenant-id: # must be set externally (sample: 00000000-0000-0000-0000-000000000000)
      token-url: https://login.microsoftonline.com/${application.security.oauth.tenant-id}/oauth2/v2.0/token
  request-logging-filter:
    enabled: false # whether to enable the request logging filter
    includeUrls:   # list of URLs to include, in ant path style
      - /**
    excludeUrls:   # list of URLs to exclude, in ant path style
      - /actuator/health/liveness
      - /actuator/health/readiness
    include-headers: true      # whether the request headers should be included in the log message
    include-payload: true      # whether the request payload (body) should be included in the log message
    include-query-string: true # whether the query string should be included in the log message
    max-payload-length: 10240  # the maximum length (in bytes) of the payload body to be included in the log message
