#######################################################################################################################
#
# Configuration settings for Swagger UI...
#
#######################################################################################################################

application:
  swagger-ui:
    application-name: Passport Status API
    authentication:
      http:
        description: |
          **Use the *JSON Web Token* authorization scheme for *service account* access.**
      oauth:
        authorization-url: ${application.authentication.oauth.authorization-uri}
        description: |
          **Use the *Azure Active Directory* authorization scheme for *Government of Canada employee* access.**
        token-url: ${application.authentication.oauth.token-uri}
    contact-name: Digital Technology Solutions
    contact-url: https://github.com/dts-stn/passport-status-api/
    description: |
      This OpenAPI document describes the key areas where developers typically engage with this API.

      ### Authentication

      To acquire a token to use with this API, you can use the following curl command:

      ```
      CLIENT_ID="{ ...your-client-id... }"
      CLIENT_SECRET="{ ...your-client-secret... }"

      curl --silent --request POST "${application.authentication.oauth.token-uri}" \
        --form "grant_type=client_credentials" \
        --form "client_id=$CLIENT_ID" --form "client_secret=$CLIENT_SECRET" \
        --form "scope=${application.authentication.oauth.auth-scopes}" | jq --raw-output ".access_token"
      ```

      The Azure Active Directory OpenID discovery endpoint can be found here: <${application.authentication.oauth.discovery-uri}>.
    tos-url: https://www.canada.ca/en/transparency/terms.html

#######################################################################################################################
#
# SpringDoc properties..
#
#######################################################################################################################

springdoc:
  pre-loading-enabled: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    oauth:
      client-id: ${application.authentication.oauth.client-id}
      scopes: ${application.authentication.oauth.auth-scopes}
      use-pkce-with-authorization-code-grant: true
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true
