#######################################################################################################################
#
# Configuration settings for Swagger UI...
#
#######################################################################################################################

application:
  swagger-ui:
    application-name: Passport Status API
    authentication:
      http:
        description: |
          **Use the *JSON Web Token* authorization scheme for *service account* access.**
      oauth:
        authorization-url: ${application.authentication.oauth.authorization-uri}
        client-id: ${application.authentication.oauth.client-id}
        description: |
          **Use the *Azure Active Directory* authorization scheme for *Government of Canada employee* access.**
        token-url: ${application.authentication.oauth.token-uri}
    contact-name: Digital Technology Solutions
    contact-url: https://github.com/dts-stn/passport-status-api/
    description: |
      This OpenAPI document describes the key areas where developers typically engage with this API.

      ### Authentication

      Some endpoints exposed by this API require Azure Active Directory authentication.<br/>
      Two OAuth authentication schemes are available: **[AuthorizationCode w/ PKCE](https://datatracker.ietf.org/doc/html/rfc7636)** for user login;
      and **[HTTP Bearer Token](https://datatracker.ietf.org/doc/html/rfc6750)** for service account login.

      To acquire a bearer token to use with this API, you can use the following curl command:

      ```
      CLIENT_ID="{ ...service-account-id... }"
      CLIENT_SECRET="{ ...service-account-secret... }"

      curl --silent --request POST "${application.authentication.oauth.token-uri}" \
        --form "grant_type=client_credentials" \
        --form "client_id=$CLIENT_ID" --form "client_secret=$CLIENT_SECRET" \
        --form "scope=${application.authentication.oauth.auth-scopes}" | jq --raw-output ".access_token"
      ```
      The Azure Active Directory OpenID discovery endpoint can be found here: <${application.authentication.oauth.discovery-uri}>.

      #### Using the *Passport Status* service account

      If you are logging in as the ***Passport Status*** service account, you must use `scope=${application.authentication.oauth.client-id}/.default`.
      Failure to do so will result in the following error message:

      > **TAADSTS90009:** The application is requesting a token for itself. This scenario is supported only if the resource that's specified is using the GUID-based application ID.

      See <https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes#aadsts-error-codes> for more information.
    tos-url: https://www.canada.ca/en/transparency/terms.html

#######################################################################################################################
#
# SpringDoc properties..
#
#######################################################################################################################

springdoc:
  pre-loading-enabled: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    oauth:
      client-id: ${application.authentication.oauth.client-id}
      scopes: ${application.authentication.oauth.auth-scopes}
      use-pkce-with-authorization-code-grant: true
  writer-with-default-pretty-printer: true
  writer-with-order-by-keys: true