apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: passport-status
commonLabels:
  app.kubernetes.io/environment: dev
nameSuffix: -dev
bases:
  - ../../../base
images:
  - name: dtsdevcontainers.azurecr.io/passport-status-api
    newTag: latest
resources:
  - namespaces.yaml
patchesStrategicMerge:
  - config-maps.yaml
  - deployments.yaml
  - ingresses.yaml