apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-api
data:
  application.yaml: |-
    application:
      data-initializer:
        run-on-startup: true
      request-logging-filter:
        enabled: true
      security:
        cors.allowed-origins:
          - http://localhost:3000
          - http://localhost:8080
          - https://passport-status-main.dev-rhp.dts-stn.com

    management:
      metrics:
        export:
          dynatrace:
            enabled: true
            v2:
              default-dimensions:
                stack: nonprod
                region: canadacentral

    spring:
      security:
        user:
          password: '{bcrypt}$2a$10$KbMtcK7Jiru.c/nqTq72buSgvw1AKOSifQbHco2qgP/LiJHK.aT3e'