apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-api
  template:
    spec:
      containers:
        - name: passport-status-api
          env:
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: passport-status-api-dev
            - name: SPRING_PROFILES_ACTIVE
              value: embedded-mongo