apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-api
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
data:
  application-local.yaml: |-
    management:
      metrics:
        export:
          dynatrace:
            enabled: true
            v2:
              default-dimensions:
                stack: nonprod
                region: canadacentral

    spring:
      security:
        user:
          password: '{bcrypt}$2a$10$KbMtcK7Jiru.c/nqTq72buSgvw1AKOSifQbHco2qgP/LiJHK.aT3e'

    application:
      security:
        cors.allowed-origins:
          - http://localhost:3000
          - http://localhost:8080
          - https://passport-status-main.dev-rhp.dts-stn.com