apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-api
data:
  application.yaml: |-
    application:
      request-logging-filter:
        enabled: true
      security:
        cors.allowed-origins:
          - http://localhost:3000
          - http://localhost:8080
          - https://passport-status-api.staging.dev-rhp.dts-stn.com

    # logging:
    #   level:
    #     '[org.springframework]': debug
    #     '[org.springframework.data.auditing.AuditingHandlerSupport]': info
    #     '[org.springframework.data.mongodb.core.MongoTemplate]': info

    management:
      metrics:
        export:
          dynatrace:
            enabled: true
            v2:
              default-dimensions:
                stack: nonprod
                region: canadacentral

    spring:
      data:
        mongodb:
          uri: mongodb://mongodb-staging.passport-status.svc.cluster.local/passport
      security:
        user:
          password: '{bcrypt}$2a$10$KbMtcK7Jiru.c/nqTq72buSgvw1AKOSifQbHco2qgP/LiJHK.aT3e'