apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-api
  namespace: passport-status
data:
  application-local.yaml: |-
    application:
      security:
        cors.allowed-origins:
          - http://localhost:3000
          - http://localhost:8080

    spring:
      security:
        user:
          password: '{bcrypt}$2a$10$KbMtcK7Jiru.c/nqTq72buSgvw1AKOSifQbHco2qgP/LiJHK.aT3e'