apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-api
  template:
    spec:
      containers:
        - name: passport-status-api
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: embedded-mongo
          # increase resources because of embedded mongo
          resources:
            requests:
              cpu: 2000m
              memory: 512Mi
            limits:
              cpu: 4000m
              memory: 2048Mi