apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-status-api
data:
  application.yaml: |-
    application:
      authentication:
        oauth:
          client-id: de3625ec-c6e6-46a6-b761-7b1039ab546a
          tenant-id: 9ed55846-8a81-4246-acd8-b1a01abfc0d1
      database-initializer:
        run-on-startup: true
      request-logging-filter:
        enabled: true
      security:
        cors.allowed-origins:
          - http://localhost:3000
          - http://localhost:8080

    # logging:
    #   level:
    #     '[org.springframework]': debug
    #     '[org.springframework.data.auditing.AuditingHandlerSupport]': info
    #     '[org.springframework.data.mongodb.core.MongoTemplate]': info