INSERT INTO status_code
  (id, code, cdo_code, description, is_active, created_by, created_date, last_modified_by, last_modified_date)
VALUES
  ('8b4ecef5-9617-4dbc-91ca-ff24b2367b66', 'UNKNOWN', '-1', 'Passport application status is unknown.', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP),
  ('57fe687e-50a6-411f-af63-2a659622127d', 'FILE_PROCESSED', '1', 'File being processed', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP),
  ('c4c3d083-39f6-4cae-bb18-1e65dd2f60a3', 'PASSPORT_WILL_BE_ISSUED', '2', 'Passport will be issued', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP),
  ('20edcb59-b217-4ed8-8378-f78184f634f2', 'PASSPORT_ISSUED_SHIPPING_CANADA_POST', '3', 'Passport Issued & Shipping Canada Post', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP),
  ('af0857c3-467a-4770-9b2b-964f1d252107', 'PASSPORT_ISSUED_SHIPPING_FEDEX', '4', 'Passport Issued & Shipping Fedex', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP),
  ('933113a5-e219-4a86-9753-fac20deeb85b', 'NOT_ACCEPTABLE_FOR_PROCESSING', '5', 'Not acceptable for processing', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP),
  ('637c1ebd-cf97-4ed4-83d3-fd0370f62b5e', 'INVALID_FILE', '99', 'Not on table, but used for files that were previously sent to DTS as legitimate files, but are now missing information that would prevent their sending an update to DTS on a following day - this will provide no record found message', true, 'flyway-community-edition', CURRENT_TIMESTAMP, 'flyway-community-edition', CURRENT_TIMESTAMP);