apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passport-status-api
    spec:
      serviceAccountName: passport-status-api
      containers:
        - name: passport-status-api
          image: dtsdevcontainers.azurecr.io/passport-status-api
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: 'true'
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30