apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-status-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passport-status-api
    spec:
      serviceAccount: passport-status-api
      containers:
        - name: passport-status-api
          image: dtsdevcontainers.azurecr.io/passport-status-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30