apiVersion: v1
kind: Service
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app.kubernetes.io/name: passport-status-api