apiVersion: v1
kind: ServiceAccount
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
rules:
  - apiGroups: [ '' ]
    resources:
      - configmaps # required by spring-cloud-starter-kubernetes-client-config
      - endpoints  # required by spring-cloud-starter-kubernetes-client
      - pods       # required by spring-cloud-starter-kubernetes-client
      - secrets    # required by spring-cloud-starter-kubernetes-client-config
      - services   # required by spring-cloud-starter-kubernetes-client
    verbs: [ 'get', 'list', 'watch' ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
subjects:
  - kind: ServiceAccount
    name: passport-status-api
roleRef:
  kind: Role
  name: passport-status-api
  apiGroup: rbac.authorization.k8s.io