apiVersion: v1
kind: ServiceAccount
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: passport-status-api
  namespace: passport-status
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
rules:
  - apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - configmaps
      - endpoints
      - pods
      - services
      - secrets
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: passport-status-api
  labels:
    app.kubernetes.io/name: passport-status-api
    app.kubernetes.io/part-of: passport-status
subjects:
  - kind: ServiceAccount
    name: passport-status-api
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: passport-status-api